rocketmq:
  producer:
    send-message-timeout: 1000
    retry-next-server: true
    group: channelMsgProducer
  consumer:
    group: gatewayMsgConsumer
spring:
  profiles:
    active: dev
  application:
    name: gateway-comet
dubbo:
  application:
    register-mode: instance
    qos-enable: false
  scan:
    base-packages: com.ngbs.nanshu.gateway.rpc
  protocol:
    prefer-serialization: hessian2
    port: 20881