rocketmq:
  producer:
    send-message-timeout: 1000
    retry-next-server: true
    group: channelMsgProducer
  consumer:
    group: gatewayMsgConsumer
spring:
  profiles:
    active: dev
  application:
    name: gateway-comet
grpc:
  logic-service: nacos://gateway-logic
  port: 10235
nacos:
  service-name: ${spring.application.name}